version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install zensical mkdocstrings[python]
    build:
      html:
        - python -m zensical build
        - mkdir -p $READTHEDOCS_OUTPUT/html/
        - cp -r site/* $READTHEDOCS_OUTPUT/html/

python:
  install:
    - method: pip
      path: .
      extra_requirements: []
