version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    post_install:
      - pip install zensical mkdocstrings[python]
    build:
      - python -m zensical build --site-dir $READTHEDOCS_OUTPUT/html

python:
  install:
    - method: pip
      path: .
      extra_requirements: []
